MVCTest01/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTest01.Controllers {
	public class ArticlesController : Controller {
		// GET: Articles
		public ActionResult Index() {
			return View();
		}
		public ActionResult Fish() {
			return View();
		}
	}
}

MVCTest01/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTest01.Controllers {
	public class BooksController : Controller {

		public ActionResult Index() {
			return View();
		}

		public ActionResult Add() {
			return View();
		}
	}
}

MVCTest01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTest01.Controllers {
	public class HomeController : Controller {
		public ActionResult Index() {
			return View();
		}

		public ActionResult About() {
			ViewBag.Message = "Your application description page.";
			return View();
		}

		public ActionResult Contact() {
			ViewBag.Message = "Your contact page.";
			return View();
		}

		public ActionResult hw() {
			ViewBag.Massage = "Hello World";
			return View();
		}

		public ActionResult ViwePage1() {
			ViewBag.Massage = "VP1";
			return View();
		}

		public ActionResult DivTest() {
			ViewBag.Massage = "Divs";
			return View();
		}
	}
}

MVCTest01/Views/Articles/Fish.cshtml
@{
	Layout = "_Articles.cshtml";
	ViewBag.Massage = "Fish";
}

<div class="col-lg-10">
	<img class="left" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Dunkleosteus_BW.jpg/220px-Dunkleosteus_BW.jpg" />
	<img class="left" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Dunkleosteus_BW.jpg/220px-Dunkleosteus_BW.jpg" />
	<img class="left" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Dunkleosteus_BW.jpg/220px-Dunkleosteus_BW.jpg" />
	<div class="col-lg-6">
		<p>
			Fish do not represent a monophyletic group, and therefore the "evolution of fish" is not studied as a single event.[5]

			Early fish from the fossil record are represented by a group of small, jawless, armored fish known as Ostracoderms. Jawless fish lineages are mostly extinct. An extant clade, the Lampreys may approximate ancient pre-jawed fish. The first jaws are found in Placodermi fossils. The diversity of jawed vertebrates may indicate the evolutionary advantage of a jawed mouth. It is unclear if the advantage of a hinged jaw is greater biting force, improved respiration, or a combination of factors.

			Fish may have evolved from a creature similar to a coral-like Sea squirt, whose larvae resemble primitive fish in important ways. The first ancestors of fish may have kept the larval form into adulthood (as some sea squirts do today), although perhaps the reverse is the case.
		</p>
	</div>
	<div class="col-lg-4">

		<img class="left" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Dunkleosteus_BW.jpg/220px-Dunkleosteus_BW.jpg" />
		<img class="left" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Dunkleosteus_BW.jpg/220px-Dunkleosteus_BW.jpg" />
	</div>
	<div class="col-lg-10">
		<p>
			The term "fish" most precisely describes any non-tetrapod craniate (i.e. an animal with a skull and in most cases a backbone) that has gills throughout life and whose limbs, if any, are in the shape of fins.[12] Unlike groupings such as birds or mammals, fish are not a single clade but a paraphyletic collection of taxa, including hagfishes, lampreys, sharks and rays, ray-finned fish, coelacanths, and lungfish.[13][14] Indeed, lungfish and coelacanths are closer relatives of tetrapods (such as mammals, birds, amphibians, etc.) than of other fish such as ray-finned fish or sharks, so the last common ancestor of all fish is also an ancestor to tetrapods. As paraphyletic groups are no longer recognised in modern systematic biology, the use of the term "fish" as a biological group must be avoided.

			Many types of aquatic animals commonly referred to as "fish" are not fish in the sense given above; examples include shellfish, cuttlefish, starfish, crayfish and jellyfish. In earlier times, even biologists did not make a distinction – sixteenth century natural historians classified also seals, whales, amphibians, crocodiles, even hippopotamuses, as well as a host of aquatic invertebrates, as fish.[15] However, according the definition above, all mammals, including cetaceans like whales and dolphins, are not fish. In some contexts, especially in aquaculture, the true fish are referred to as finfish (or fin fish) to distinguish them from these other animals.

			A typical fish is ectothermic, has a streamlined body for rapid swimming, extracts oxygen from water using gills or uses an accessory breathing organ to breathe atmospheric oxygen, has two sets of paired fins, usually one or two (rarely three) dorsal fins, an anal fin, and a tail fin, has jaws, has skin that is usually covered with scales, and lays eggs.

			Each criterion has exceptions. Tuna, swordfish, and some species of sharks show some warm-blooded adaptations—they can heat their bodies significantly above ambient water temperature.[13] Streamlining and swimming performance varies from fish such as tuna, salmon, and jacks that can cover 10–20 body-lengths per second to species such as eels and rays that swim no more than 0.5 body-lengths per second.[13] Many groups of freshwater fish extract oxygen from the air as well as from the water using a variety of different structures. Lungfish have paired lungs similar to those of tetrapods, gouramis have a structure called the labyrinth organ that performs a similar function, while many catfish, such as Corydoras extract oxygen via the intestine or stomach.[16] Body shape and the arrangement of the fins is highly variable, covering such seemingly un-fishlike forms as seahorses, pufferfish, anglerfish, and gulpers. Similarly, the surface of the skin may be naked (as in moray eels), or covered with scales of a variety of different types usually defined as placoid (typical of sharks and rays), cosmoid (fossil lungfish and coelacanths), ganoid (various fossil fish but also living gars and bichirs), cycloid, and ctenoid (these last two are found on most bony fish).[17] There are even fish that live mostly on land. Mudskippers feed and interact with one another on mudflats and go underwater to hide in their burrows.[18] The catfish Phreatobius cisternarum lives in underground, phreatic habitats, and a relative lives in waterlogged leaf litter.[19][20]

			Fish range in size from the huge 16-metre (52 ft) whale shark to the tiny 8-millimetre (0.3 in) stout infantfish.

			Fish species diversity is roughly divided equally between marine (oceanic) and freshwater ecosystems. Coral reefs in the Indo-Pacific constitute the center of diversity for marine fishes, whereas continental freshwater fishes are most diverse in large river basins of tropical rainforests, especially the Amazon, Congo, and Mekong basins. More than 5,600 fish species inhabit Neotropical freshwaters alone, such that Neotropical fishes represent about 10% of all vertebrate species on the Earth. Exceptionally rich sites in the Amazon basin, such as Cantão State Park, can contain more freshwater fish 
		</p>
	</div>
</div>

MVCTest01/Views/Articles/Index.cshtml
@{
	Layout = "_Articles.cshtml";
	ViewBag.Massage = "Home";
}

<div>
	<div class="col-lg-5">
		<p>
			Lorem Ipsum is simply dummy text of the printing and typesetting industry.
			Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
			when an unknown printer took a galley of type and scrambled it to make a type specimen book.
			It has survived not only five centuries,
			but also the leap into electronic typesetting,
			remaining essentially unchanged.
			It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
			and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
		</p>
	</div>
	<div class="col-lg-5">
		<p>
			Contrary to popular belief,
			Lorem Ipsum is not simply random text.
			It has roots in a piece of classical Latin literature from 45 BC,
			making it over 2000 years old. Richard McClintock,
			a Latin professor at Hampden-Sydney College in Virginia,
			looked up one of the more obscure Latin words, consectetur,
			from a Lorem Ipsum passage,
			and going through the cites of the word in classical literature,
			discovered the undoubtable source.
			Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,
			written in 45 BC. This book is a treatise on the theory of ethics,
			very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..",
			comes from a line in section 1.10.32.
			<br />
			The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.
			Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,
			accompanied by English versions from the 1914 translation by H. Rackham.
		</p>
	</div>
	<div class="col-sm-10">
		<p>
			"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system,
			and expound the actual teachings of the great explorer of the truth,
			the master-builder of human happiness.
			No one rejects, dislikes, or avoids pleasure itself, because it is pleasure,
			but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.
			Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain,
			but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.
			To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it?
			But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences,
			or one who avoids a pain that produces no resultant pleasure?"
		</p>
	</div>
</div>

MVCTest01/Views/Articles/_Articles.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.Title = "DivTest";
}

<div class="siteMain">
	<div class="subHeader">
		<div class="imgHeader">
			<img src="https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg" />
		</div>
		<div class="txtHeader"><span class="col-lg-1"></span><h2>@ViewBag.Massage</h2></div>

	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-2 col-xs-2" id="sidebar" role="navigation">
				<ul class="nav" style="margin-left: 0px">
					<li class="active">@Html.ActionLink("Home", "Index", "Articles")</li>
					<li>@Html.ActionLink("Fish", "Fish", "Articles")</li>
					<li><a href="#">Applection </a></li>
					<li><a href="#">BullShit</a></li>
				</ul>
			</div>
			<div class="col-lg-10 container">
					@RenderBody()
				
			</div>
		</div>
	</div>
</div>

MVCTest01/Views/Books/Add.cshtml
@{
	ViewBag.Title = "Add Book";
}

<h1>Add a new Book</h1>
<script>
	function addbook(){

	}
</script>
<div class="input-group">
	<table class="table-condensed">
		<tr>
			<td class="text-left">Title: </td>
			<td><input id="tInput" class="input-sm" type="text" /></td>
		</tr>
		<tr>
			<td class="text-left">Autor: </td>
			<td><input id="aInput" class="input-sm" type="text" /></td>
		</tr>
	</table>
	<input class="btn" type="button" value="Submit" onclick="addBook()"/>
</div>

MVCTest01/Views/Books/Index.cshtml
@{
	ViewBag.Tile = "Books";
}

<div class="jumbotron">
	<h1>
		Books
	</h1>
</div>
<div class="btn-link">
	@*@Html.ActionLink("add", "ADD")*@
</div>
<div class="list-group">
	hello World
	
</div>

MVCTest01/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCTest01/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCTest01/Views/Home/DivTest.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.Title = "DivTest";
}

<div class="siteMain">
	<div class="subHeader">
		<div class="imgHeader">
			<img src="https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg" />
		</div>
		<div class="txtHeader"><h2>My Page</h2></div>

	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-2 col-xs-2"  id="sidebar" role="navigation">
				<ul class="nav" style="margin-left: 0px">
					<li class="active"><a href="#">Home</a></li>
					<li><a href="#">Fish</a></li>
					<li><a href="#">Applection </a></li>
					<li><a href="#">BullShit</a></li>
				</ul>
			</div>
			<div class="bottom">

				<div class="col-lg-4">
					<p>
						Lorem Ipsum is simply dummy text of the printing and typesetting industry.
						Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
						when an unknown printer took a galley of type and scrambled it to make a type specimen book.
						It has survived not only five centuries,
						but also the leap into electronic typesetting,
						remaining essentially unchanged.
						It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
						and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
					</p>
				</div>
				<div class="col-sm-4">
					<p>
						Contrary to popular belief,
						Lorem Ipsum is not simply random text.
						It has roots in a piece of classical Latin literature from 45 BC,
						making it over 2000 years old. Richard McClintock,
						a Latin professor at Hampden-Sydney College in Virginia,
						looked up one of the more obscure Latin words, consectetur,
						from a Lorem Ipsum passage,
						and going through the cites of the word in classical literature,
						discovered the undoubtable source.
						Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,
						written in 45 BC. This book is a treatise on the theory of ethics,
						very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..",
						comes from a line in section 1.10.32.
						<br />
						The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.
						Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,
						accompanied by English versions from the 1914 translation by H. Rackham.
					</p>
				</div>
				@*<br style="clear:both" />*@
				<div class="col-sm-push-1 col-sm-10">
					<p>
						"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

MVCTest01/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCTest01/Views/Home/ViewPage1.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    hello world
</div>

MVCTest01/Views/Home/hw.cshtml
<div>
	<p>Hello World!!!!</p>
</div>
<table class="t1">
	@{for (int i = 1; i < 10; i++) {
			<tr>
				@{for (int j = 1; j < 10; j++) {
						<td>@(i * j)</td>
						}
				}
			</tr>
		}
	}
</table>

MVCTest01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar "></span>
                </button>
                @Html.ActionLink("MVCTest01", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Hello World","hw", "Home")</li>
                    <li>@Html.ActionLink("Div Test","DivTest", "Home")</li>
					<li>@Html.ActionLink("Books", "Index", "Books")</li>
					<li>@Html.ActionLink("Articles", "Index", "Articles")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>